name: tucamion
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^3.5.0
  flutter:
    sdk: flutter
  connectivity_plus: ^2.0.2
  google_fonts: ^6.1.0
  http: any
  google_maps_flutter: ^2.0.3
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_form_builder: ^9.1.1
  permission_handler: ^10.1.0
  shared_preferences: ^2.0.8
  flutter_cache_manager: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/delivery-truck-1.png
    - assets/images/cloudy-1.png
    - assets/images/cloudy-2.png
    - assets/images/driver-1.png
    - assets/images/package-1.png
    - assets/images/package.png
    - assets/images/tracking.png
